In [21]:
import numpy as np
A = np.array([[2,   1],
              [10, -2]])
B = np.array([13, 44]).reshape(2, 1)

A_inv = np.linalg.inv(A)

ans = A_inv.dot(B)
print(ans)

[[5.]
 [3.]]


In [22]:

A = np.mat('2,1; 10,-2')    
b = np.mat('13,44').T       
r = np.linalg.solve(A,b)  
print(r)

[[5.]
 [3.]]


In [23]:
A = np.array([[3,2],[2,3],[2,-2]])
a_svd = np.linalg.svd(A) 
a_svd

(array([[-7.07106781e-01,  2.35702260e-01, -6.66666667e-01],
        [-7.07106781e-01, -2.35702260e-01,  6.66666667e-01],
        [-1.88794506e-16,  9.42809042e-01,  3.33333333e-01]]),
 array([5., 3.]),
 array([[-0.70710678, -0.70710678],
        [ 0.70710678, -0.70710678]]))

In [24]:
A = np.array([[3,2,1],[2,3,1],[2,-2,1]])
a_eigen = np.linalg.eig(A) 
a_eigen

(array([5.        , 1.00000002, 0.99999998]),
 array([[-7.07106781e-01, -2.35702256e-01,  2.35702265e-01],
        [-7.07106781e-01, -2.35702267e-01,  2.35702254e-01],
        [ 4.06449421e-18,  9.42809041e-01, -9.42809042e-01]]))

In [25]:
from fractions import Fraction
print(Fraction(1/(2**(1/2))))

1592262918131443/2251799813685248


In [26]:
(-80538738812075974)**3 + 80435758145817515**3 + 12602123297335631**3

42